name: Release Application

on: # ADD YOUR TRIGGER HERE

env: # ADD YOUR ENVIRONMENT VARIABLES HERE

jobs:
  deploy:
    if: # ADD YOUR CONDITION HERE
    environment: development
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login OpenShift
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: <<TODO>>
          openshift_token: <<TODO>>
          namespace: <<TODO>>

      - name: Apply Openshift YAML
        run: |
          # ADD YOUR COMMANDS HERE
